# Generated by Django 4.0.3 on 2022-03-21 01:48

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Especificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacao', models.CharField(blank=True, max_length=30, null=True)),
                ('raca', models.CharField(blank=True, max_length=30, null=True)),
                ('porte', models.CharField(blank=True, max_length=30, null=True)),
                ('idade', models.CharField(blank=True, max_length=30, null=True)),
                ('composicao', models.CharField(blank=True, max_length=350, null=True)),
                ('cor', models.CharField(blank=True, max_length=350, null=True)),
                ('fragrancia', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.FloatField(blank=True, max_length=6, null=True)),
                ('frequencia_recomendada', models.IntegerField(blank=True, null=True)),
                ('dimensoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagem', stdimage.models.StdImageField(upload_to='produto_imagens/%Y/%m/')),
                ('preco', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('preco_promocional', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.categoria')),
                ('especificacoes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.especificacoes')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.marca')),
            ],
        ),
    ]
