# Generated by Django 4.0.3 on 2022-05-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='frete',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='PEDIDO CRIADO', max_length=13),
        ),
    ]
