# Generated by Django 4.0.3 on 2022-05-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_pedido_frete_remove_pedido_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
