# Generated by Django 4.0.3 on 2022-05-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='material',
        ),
    ]
